name: End-To-End-Tests-CI

on:
  workflow_run:
    workflows: [API-CD]
    types: [completed]
  pull_request:
    paths:
      - 'end-to-end-tests/**'
  workflow_dispatch:

env:
  NODE_VERSION: 16
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_ARTIFACT_WRITER }}
  GITHUB_TOKEN: ${{ secrets.GH_PAT_PRIVATE_REPOS_FULL_AND_ALL_OTHER_RESOURCES_READ_ACCESS }}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm install -g npm
      - run: npm ci
      - run: npm run lint-check --workspace end-to-end-tests

  code-format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm install -g npm
      - run: npm ci
      - run: npm run format-check --workspace end-to-end-tests

  end-to-end-tests:
    needs:
      - lint
      - code-format
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2
      - name: Login to GCP Registry
        run: echo $GOOGLE_CREDENTIALS | docker login -u "_json_key" --password-stdin https://us-central1-docker.pkg.dev
        shell: bash 
      - name: Launch Virtual Cart
        run: docker-compose -f ./end-to-end-tests/docker-compose.yml up -d
        shell: bash
      - name: Setup NodeJS Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm install -g npm
      - run: npm ci
      - run: npm run build --workspace api-sdk-ts 
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start --workspace ui-checkout
          wait-on: 'http://localhost:3000'
          command: npm run test --workspace end-to-end-tests
          browser: chrome
